version: "3"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    # depends_on:
    #   - wordpress
    ports:
      - 443:443
    restart: always
