version: "3"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    restart: always
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_nginx:/var/www/html/
    ports:
      - "9000:9000"
    env_file:
      - .env
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - wordpress_nginx:/var/www/html
    depends_on:
      - wordpress
    ports:
      - 443:443
    env_file:
      - .env
    restart: always
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    depends_on:
      - mariadb
    ports:
      - "6379:6379"
    env_file:
      - .env
    restart: always
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    ports:
      - "21:21"
    env_file:
      - .env
    networks:
      - inc_network
    restart: always
  website:
    build: ./requirements/bonus/website
    container_name: website
    ports:
      - "3000:3000"
    restart: always
  backup:
    build: ./requirements/bonus/backup
    container_name: backup
    depends_on:
      - mariadb
    ports:
      - "1337:1337"
    volumes:
      - mariadb_data:/home/backup/
    restart: always
networks:
  inc_network:
volumes:

  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/nhakkaou/db'

  wordpress_nginx:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/nhakkaou/data/wp'