version: "3"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - /home/nhakkaou/db/:/var/lib/mysql
    restart: always

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - /home/nhakkaou/data/wp:/var/www/html/
    ports:
      - "9000:9000"
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - /home/nhakkaou/data/wp:/var/www/html
    depends_on:
      - wordpress
    ports:
      - 443:443
    restart: always
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    restart: always
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    depends_on:
      - mariadb
    ports:
      - "6379:6379"
    restart: always
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    depends_on:
      - mariadb
    ports:
      - "21:21"
    restart: always
  website:
    build: ./requirements/bonus/website
    container_name: website
    ports:
      - "3000:3000"
    restart: always
  backup:
    build: ./requirements/bonus/backup
    container_name: backup
    depends_on:
      - mariadb
    ports:
      - "4242:4242"
    volumes:
      - /home/nhakkaou/db/:/backup/
    restart: always

