version: "3"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - myapp:/var/lib/mysql
    restart: always

  wordpress:
    depends_on:
      - db
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - hostPath:/home/wp
    ports:
      - "9000:9000"
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - hostPath:/var/wwww/html
    depends_on:
      - wordpress
    ports:
      - 443:443
    restart: always
volumes:
  myapp:
  hostPath:
