version: "3"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - myapp:/var/lib/mysql
    restart: always

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - hostPath:/var/www/html
    ports:
      - "9000:9000"
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - hostPath:/var/wwww/html
    depends_on:
      - wordpress
    ports:
      - 443:443
    restart: always
volumes:
  myapp:
  hostPath:
    driver: local
    driver_opts:
    type: 'none'
    o: bind
    device: /home/nhakkaou/data/wp

